name: dart_fsnotify
description: >
  Cross-platform filesystem watcher for Dart. Watch files and directories
  for create, write, remove, rename, and chmod events — inspired by fsnotify.
version: 0.1.0
repository: https://github.com/tobibamidele/dart-fsnotify

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  async: ^2.13.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
